### ISSUE TITLE
Error calling ListQueues

### ISSUE THREAD

**Issue by zdzolton** [jhs/cqs#1]
Hi,

I get the following error/stacktrace when trying to call ListQueues:

```
Error: Invalid protocol
    at [object Object].request (/path/to/my/app/node_modules/cqs/node_modules/request/main.js:194:34)
    at request (/path/to/my/app/node_modules/cqs/node_modules/request/main.js:332:5)
    at Object.req_json (/path/to/my/app/node_modules/cqs/lib.js:68:10)
    at Object.list_queues (/path/to/my/app/node_modules/cqs/queue.js:296:7)
    at Object.default_wrapper [as ListQueues] (/path/to/my/app/node_modules/cqs/api.js:38:22)
```

This is after I call `cqs.defaults()` with an argument like the following:

```
{ couch: 'http://username:password@localhost:5984', db: 'cqs-development' }
```

(Assume that I used my local admin account for the defaults couch string...)

Anyways, I'm excited to continue trying out CQS, and if you could help me figure this out I'd really appreciate it! So, please let me know any other details I can provide to help.

Cheers,
Zach

P.S. I'm on node.js v0.4.8 and CQS v0.3.0.

**Comment by zdzolton** [comment]
Ah, I originally missed that you assign the results of `cqs.defaults()` back to the cqs variable:

```
cqs = cqs.defaults({ "couch": "https://user:password@example.iriscouch.com"
                   , "db"   : "cqs_queue"
                   });
```

My bad.
